# Main theme library.
global:
  css:
    base:
      css/base/elements.css: {}
    component:
      css/component/menu.css: {}
      css/component/block.css: {}
      css/component/breadcrumb.css: {}
      css/component/field.css: {}
      css/component/table.css: {}
      css/component/header.css: {}
      css/component/footer.css: {}
      css/component/buttons.css: {}
      css/component/sidebar.css: {}
    layout:
      css/layout/grid.css: {}
      css/layout/layout.css: {}
    theme:
      css/theme/print.css: { media: print }
  js:
    js/flexi-style.js: {}
  dependencies:
    - core/jquery
    - core/drupal

owl_carousel:
  css:
    component:
      css/component/carousel.css: { weight: -10 }

top_header:
  css:
    component:
      css/component/header-top.css: { weight: -9 }

messages:
  css:
    component:
      css/component/messages.css: { weight: 0 }

pager:
  css:
    component:
      css/component/pager.css: { weight: 0 }

comment:
  css:
    component:
      css/component/comment.css: { weight: 0 }

tabs:
  css:
    component:
      css/component/tabs.css: { weight: -1 }

form:
  css:
    component:
      css/component/form.css: { weight: -9 }

views:
  css:
    component:
      css/component/views.css: {weight: -8 }

navigation:
  css:
    component:
      css/component/navigation.css: { weight: -7 }
node:
  css:
    component:
      css/component/node.css: {weight: -6 }

# Fonts
helvetica:
  css:
    component:
      fonts/helvetica.css: {}

verdana:
  css:
    component:
      fonts/verdana.css: {}

roboto:
  css:
    component:
      fonts/roboto.css: {}
      //fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap: { type: external }

lato:
  css:
    component:
      fonts/lato.css: {}
      //fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap: { type: external }

poppins:
  css:
    component:
      fonts/poppins.css: {}
      //fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap: { type: external }

open-sans:
  css:
    component:
      fonts/open-sans.css: {}
      //fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap: { type: external }

# icons
fontawesome:
  css:
    component:
      fonts/fontawesome/css/fontawesome.min.css: {}
      fonts/fontawesome/css/brands.css: {}
      fonts/fontawesome/css/solid.css: {}

google-material:
  css:
    component:
      fonts/google-material/google-material.css: {}
